#!/usr/bin/env bash
# vim: set ft=sh

docker_required() {
    echo ""
    echo "É necessário permissão de super usuário"
    sudo true

    # docker
    if [[ `which docker` == '' ]]; then
        echo "Docker não está instalado."
        exit 0
    fi

    # docker-compose
    if [[ `which docker-compose` == '' ]]; then
        echo "Docker-compose não está instalado, ou ele não está na pasta /usr/bin."
        exit 0
    fi

    # compilando a maquina
    echo ""
    echo "Será iniciado o build da maquina do portal."
    echo "Tenha paciência, isso irá demorar um pouco. :)"
    echo "Vai lá e pega um café, a espera será mais feliz."
    echo ""
}

docker_start() {
    # start
    docker_required

    # Baixando as imagens
    docker-compose pull

    #iniciando as imagens
    docker_up_containers

    # Configurando o ambiente
    docker_base
}

docker_build () {
    # start
    docker_required

    # remove todos os containers
    docker-compose down

    # executa o build
    sudo docker-compose build

    #configurando o banco de dados
    docker-compose up -d
    sleep 10

    # configurando o ambiente
    docker_base

    # faz as últimas configurações
    docker_up_containers_reset_db
}

docker_base() {

    # Permissão de escrita
    cd ..
    sudo chmod 777 -R workaholic
}


docker_up_containers() {
    docker-compose start
}

docker_down_containers() {
    docker-compose stop
}

docker_up_containers_with_logs() {
    docker_up_containers
    docker-compose logs --tail=50 -f
}

docker_up_containers_reset_db() {
    #flag
    chmod 777 resources/reset_db
    echo "1" > resources/reset_db

    docker_down_containers
    docker_up_containers

    #up
    docker_up_containers_with_logs
}

ambiemtum_replace_commands() {
    curl -L https://github.com/codecasts/ambientum/raw/master/commands.bash -o ~/.ambientum_rc
    source ~/.ambientum_rc
    cd -
}

echo "Seja bem-vindo ao menu de setup."
echo "Por favor escolha uma das opções abaixo:"

echo "1 - Deploy com o Docker"
echo "2 - Iniciar os containers"
echo "3 - Iniciar os containers com logs"
echo "4 - Iniciar os containers e resetar o banco de dados"
echo "5 - Desligar os containers"
echo "6 - Adicionar comandos locais"

if [ "$1" == "" ]; then
    echo -n "Digite sua opção: "
    read -n 1 option
    echo ""
else
    option="$1"
fi
if [ "$option" == "1" ]; then
    docker_build
elif [ "$option" == "2" ]; then
    docker_up_containers
elif [ "$option" == "3" ]; then
    docker_up_containers_with_logs
elif [ "$option" == "4" ]; then
    docker_up_containers_reset_db
elif [ "$option" == "5" ]; then
    docker_down_containers
elif [ "$option" == "6" ]; then
    ambiemtum_replace_commands
else
    echo ""
    echo ":) Você quase acertou. Agora tente uma opção entre 1 e 5"
fi
